### ISSUE TITLE
DEVILS folder and file to be removed?

### ISSUE THREAD

**Issue by lacan** [BIOP/ijp-DEVILS#5]
@NicoKiaru is this needed?
https://github.com/BIOP/ijp-DEVILS/tree/master/DEVILS

**Comment by NicoKiaru** [comment]
interesting! no it's not needed

**Comment by NicoKiaru** [comment]
Extra files removed in https://github.com/BIOP/ijp-DEVILS/commit/7975a773d3a9a116944aeebc7695e83846cd8e99
